#version 460

layout(local_size_x_id = 0) in;

layout(push_constant) uniform Push {
    uint count;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Src { float src[]; };
layout(std430, set = 0, binding = 1) restrict writeonly buffer Dst { float dst[]; };

shared float partial[gl_WorkGroupSize.x];

// snippet:begin sequential
void main() {
    uint t = gl_LocalInvocationIndex;
    uint i = gl_GlobalInvocationID.x;
    partial[t] = i < push.count ? src[i] : 0.0;
    barrier();
    for (uint stride = gl_WorkGroupSize.x / 2; stride > 0; stride /= 2) {
        if (t < stride) partial[t] += partial[t + stride];
        barrier();
    }
    if (t == 0) dst[gl_WorkGroupID.x] = partial[0];
}
// snippet:end sequential
