#version 460
#extension GL_KHR_shader_subgroup_arithmetic : require

layout(local_size_x_id = 0) in;
layout(constant_id = 1) const uint ITEMS = 8;

layout(push_constant) uniform Push {
    uint count;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Src { float src[]; };
layout(std430, set = 0, binding = 1) restrict writeonly buffer Dst { float dst[]; };

shared float subgroupSums[gl_WorkGroupSize.x];

void main() {
    uint first = gl_WorkGroupID.x * gl_WorkGroupSize.x * ITEMS + gl_LocalInvocationIndex;
    float sum = 0.0;
    for (uint k = 0; k < ITEMS; ++k) {
        uint i = first + k * gl_WorkGroupSize.x;
        if (i < push.count) sum += src[i];
    }
    // snippet:begin subgroup
    sum = subgroupAdd(sum);
    if (subgroupElect()) subgroupSums[gl_SubgroupID] = sum;
    barrier();
    if (gl_SubgroupID == 0) {
        sum = 0.0;
        for (uint s = gl_SubgroupInvocationID; s < gl_NumSubgroups; s += gl_SubgroupSize) {
            sum += subgroupSums[s];
        }
        sum = subgroupAdd(sum);
        if (subgroupElect()) dst[gl_WorkGroupID.x] = sum;
    }
    // snippet:end subgroup
}
