if(NOT TARGET glfw)
  message(STATUS "u4_glport: skipped, GLFW was not found")
  return()
endif()
if(NOT APPLE)
  find_path(VKF_GLCOREARB_DIR GL/glcorearb.h)
  if(NOT VKF_GLCOREARB_DIR)
    message(STATUS "u4_glport: skipped, GL/glcorearb.h was not found")
    return()
  endif()
endif()
vkf_program(u4_glport main.cpp gl_renderer.cpp vk_renderer.cpp)
target_link_libraries(u4_glport PRIVATE u4_shared glfw)
if(NOT APPLE)
  target_include_directories(u4_glport PRIVATE ${VKF_GLCOREARB_DIR})
endif()
set_target_properties(u4_glport PROPERTIES LINK_LIBRARIES_STRATEGY REORDER_FREELY)
vkf_shaders(u4_glport scene.vert scene.frag)
