#version 460

layout(local_size_x_id = 0) in;
layout(constant_id = 1) const uint ITEMS = 4;

layout(push_constant) uniform Push {
    uint count;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Offsets { uint offsets[]; };
layout(std430, set = 0, binding = 1) restrict buffer Data { uint data[]; };

// snippet:begin add
void main() {
    uint offset = offsets[gl_WorkGroupID.x];
    uint first = gl_WorkGroupID.x * gl_WorkGroupSize.x * ITEMS + gl_LocalInvocationIndex;
    for (uint k = 0; k < ITEMS; ++k) {
        uint i = first + k * gl_WorkGroupSize.x;
        if (i < push.count) data[i] += offset;
    }
}
// snippet:end add
