#version 460

layout(local_size_x = 256) in;

layout(push_constant) uniform Push {
    float a;
    uint n;
} push;

// snippet:begin bindings
layout(std430, set = 0, binding = 0) readonly buffer X { float x[]; };
layout(std430, set = 0, binding = 1) buffer Y { float y[]; };
// snippet:end bindings

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < push.n) {
        y[i] = push.a * x[i] + y[i];
    }
}
