#version 460

layout(local_size_x_id = 0) in;

layout(push_constant) uniform Push {
    uint count;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Values { uint values[]; };
layout(std430, set = 0, binding = 1) restrict writeonly buffer Flags { uint flags[]; };

// snippet:begin flags
bool keep(uint value) {
    return value % 3 == 0;
}

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < push.count) flags[i] = keep(values[i]) ? 1 : 0;
}
// snippet:end flags
