#version 460

layout(local_size_x = 256) in;

layout(push_constant) uniform Push {
    uint count;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Src { float src[]; };
layout(std430, set = 0, binding = 1) restrict writeonly buffer Dst { float dst[]; };

// snippet:begin copy-float
void main() {
    uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    for (uint i = gl_GlobalInvocationID.x; i < push.count; i += stride) {
        dst[i] = src[i];
    }
}
// snippet:end copy-float
