#version 460

layout(local_size_x = 256) in;

layout(push_constant) uniform Push {
    uint count;
} push;

// snippet:begin copy-vec4
layout(std430, set = 0, binding = 0) restrict readonly buffer Src { vec4 src[]; };
layout(std430, set = 0, binding = 1) restrict writeonly buffer Dst { vec4 dst[]; };

void main() {
    uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    for (uint i = gl_GlobalInvocationID.x; i < push.count / 4; i += stride) {
        dst[i] = src[i];
    }
}
// snippet:end copy-vec4
