if(NOT TARGET glfw)
  message(STATUS "u4_textured: skipped, GLFW was not found")
  return()
endif()
vkf_program(u4_textured main.cpp)
target_link_libraries(u4_textured PRIVATE u4_present u4_shared)
set_target_properties(u4_textured PROPERTIES LINK_LIBRARIES_STRATEGY REORDER_FREELY)
vkf_shaders(u4_textured textured.vert bindless.frag fixed.frag)
