#version 460

layout(local_size_x = 256) in;

layout(push_constant) uniform Push {
    uint words;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Data { uint data[]; };
layout(std430, set = 0, binding = 1) restrict buffer Bins { uint bins[]; };

// snippet:begin global
void main() {
    uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    for (uint i = gl_GlobalInvocationID.x; i < push.words; i += stride) {
        uint word = data[i];
        for (int byte = 0; byte < 4; ++byte) {
            atomicAdd(bins[bitfieldExtract(word, 8 * byte, 8)], 1u);
        }
    }
}
// snippet:end global
