#version 460

layout(local_size_x = 256) in;
const uint BINS = 256;

layout(push_constant) uniform Push {
    uint words;
} push;

layout(std430, set = 0, binding = 0) restrict readonly buffer Data { uint data[]; };
layout(std430, set = 0, binding = 1) restrict buffer Bins { uint bins[]; };

// snippet:begin shared
shared uint counts[BINS];

void main() {
    for (uint b = gl_LocalInvocationIndex; b < BINS; b += gl_WorkGroupSize.x) {
        counts[b] = 0;
    }
    barrier();

    uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    for (uint i = gl_GlobalInvocationID.x; i < push.words; i += stride) {
        uint word = data[i];
        for (int byte = 0; byte < 4; ++byte) {
            atomicAdd(counts[bitfieldExtract(word, 8 * byte, 8)], 1u);
        }
    }
    barrier();

    for (uint b = gl_LocalInvocationIndex; b < BINS; b += gl_WorkGroupSize.x) {
        if (counts[b] != 0) atomicAdd(bins[b], counts[b]);
    }
}
// snippet:end shared
